# Generated by Django 3.2.3 on 2021-07-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmovie',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
