# Generated by Django 3.2.3 on 2021-07-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210723_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('score', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
