# Generated by Django 3.2.3 on 2021-07-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_moviereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='nmovie',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='nmovie',
            name='rating',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
