# Generated by Django 3.2.3 on 2021-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210727_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nmovie',
        ),
    ]
